### ISSUE TITLE
Windows 10 21H2 Host:  Add-VMGPUPartitionAdapter Error

### ISSUE THREAD

**Issue by gawainXX** [jamesstringerparsec/Easy-GPU-P#5]
When running the script on a Windows 10, 21H2 host, the following error was encountered.

```
Add-VMGpuPartitionAdapter : A parameter cannot be found that matches parameter name 'InstancePath'.

+     Add-VMGpuPartitionAdapter -VMName $VMName -InstancePath $DevicePa ...
+                                               ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Add-VMGpuPartitionAdapter], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.HyperV.PowerShell.Commands.AddVMGpuPartitionAdapter
 ```

Omitting the -InstancePath parameter on line 4251 seems to resolve the issue,
Add-VMGpuPartitionAdapter -VMName $VMName

I could find any available parameters that seemed like they would be a direct replacement for -InstancePath is that parameter perhaps depreciated? I have not seen it referenced in other GPU-P guides.

Can it be removed or are there instances where it's required such as Laptops with Switching Graphics?

**Comment by jamesstringerparsec** [comment]
It's part of Windows 11, useful if you want to specify which GPU is assigned.  

I lowered the requirements to Windows 10 last week but it's causing a lot of problems due to Windows 10 missing functionality compared to Windows 11.  

Specifying the adapter means I know for sure which adapter is passed to the device, this is important for knowing with confidence which GPU Driver to copy to the VM. 

Windows 10 automatically selects the GPU it assigns to the VM  and also offers no way after the fact to query which device has been assigned to the VM.  

I need to find out if there is something I can rely on with the Windows 10 assignment, such as "Windows will always pick index 0 in a multi GPU system"

**Comment by jamesstringerparsec** [comment]
Fixed with "AUTO" mode in https://github.com/jamesstringerparsec/Easy-GPU-P/commit/47ac9e9f86f2e0bae1ff8a29c26753fcd6221191
